@startuml
'https://plantuml.com/sequence-diagram

'https://plantuml.com/sequence-diagram

title WHEP Endpoint (https://datatracker.ietf.org/doc/draft-ietf-wish-whip/)


== Subscribe a Stream via WHEP ==
Client -> SFU: POST /whep
note right
content-type: "application/sdp"

payload:
{
    "sId": "defaultroom",
    "streamId": "streamId",
}

header:
Authorization: Bearer <JWT> {
    userId: userid
}
end note

Client <-- SFU: 201
note right
Response:
{
    "streamId": "streamId",
    "sessionId": "sessionId",
    "offer": {
        "type": "offer",
        "sdp": "..."
    } as RTCSessionDescription
}

Access-Control-Expose-Headers: Location

Info:
- Offer should use "recvonly"
end note


Client -> SFU: PATCH /whep
note right
content-type: "application/sdp"

payload:
{
    "sessionId": "sessionId",
    "answer": {
        "type": "answer",
        "sdp": "..."
    } as RTCSessionDescription
}

header:
Authorization: Bearer <JWT> {
    userId: userid
}

Info:
- Answer should use "sendonly"
end note

Client <-- SFU: 200
note right
Response:
{}
end note
== ICE Gathering ==
Client -> SFU: PATCH /ice
note right
content-type: "application/trickle-ice-sdpfrag"

payload:
{
    "sessionId": "sessionId",
    "type": "trickle" | "restart"
    "candidate": {
        "candidate": "..",
    } as RTCIceCandidate
}

header:
Authorization: Bearer <JWT> {
    userId: userid
}
end note
Client <-- SFU: 204

== ICE Restart ==
Client -> SFU: PATCH /ice-restart
note right
content-type: "application/trickle-ice-sdpfrag"

payload:
{
    "sessionId": "sessionId",
    "offer": {
        "type": "offer",
        "sdp": "..."
    } as RTCSessionDescription
}

header:
Authorization: Bearer <JWT> {
    userId: userid
}
end note
Client <-- SFU: 200

== Delete ==
Client -> SFU: Delete /whep
note right
content-type: "application/trickle-ice-sdpfrag"

payload:
{
    "sessionId": "sessionId",
}

header:
Authorization: Bearer <JWT> {
    userId: userid
}
end note
Client <-- SFU: 200
@enduml
