@startuml
'https://plantuml.com/sequence-diagram

title Get or Update a Receiving Stream

autonumber
== Subscriber ==

SFU -> Client: offer
note right
{
    method: offer,
    params: {
        "type": "offer",
        "sdp": "..."
    } as RTCSessionDescription
    id: uuid-subscriber
}
end note

Client -> SFU: answer
note right
{
    method: answer,
    params: {
        "desc": {
            "type": "answer",
            "sdp": "..."
        } as RTCSessionDescription
    },
    id: uuid-subscriber
}
end note
@enduml