@startuml
'https://plantuml.com/class-diagram
class Space {
    id: string
}

class LiveStream {
    id: string
    resourceUrl: string
}

'LiveStream "1" <-- "1..n" RTPStream
Space "1" <-- "1..n" LiveStream

LiveStream - Transcoder
Transcoder - Subscriber
Subscriber - RTPStream
@enduml
