@startuml
'https://plantuml.com/class-diagram

package engine {
    class Publisher {
        userID string
        conn   *RTCPeerConnection
    }

    class Subscriber {
        userID string
        conn   *RTCPeerConnection
        streams [ ]*SubscribersStream
    }
    class PublicationStream {
        publisher *Publisher
        streamID: <room>:<id>:<domain>
    }
    class SubscribersStream {
        subscriber *Subscriber
        publication *PublicationStream
    }

    class RTPStream  {
        Id
        audioTrack *webrtc.TrackLocalStaticRTP
        videoTrack *webrtc.TrackLocalStaticRTP
    }

    Space --> Publisher
    Space --> PublicationStream

    Publisher -> PublicationStream
    SubscribersStream "1-n"<-right---->"1" Subscriber: "             "


    PublicationStream "1" <-right----"0-n"  SubscribersStream: "          "
    RTPStream <|-- PublicationStream
    RTPStream <|-- SubscribersStream


}


@enduml
